const types = {
	GET_ALL_PLANTS_START: 'GET_ALL_PLANTS_START',
	GET_ALL_PLANTS_SUCCESS: 'GET_ALL_PLANTS_SUCCESS',
	GET_ALL_PLANTS_FAILURE: 'GET_ALL_PLANTS_FAILURE',

	GET_PLANT_START: 'GET_PLANT_START',
	GET_PLANT_SUCCESS: 'GET_PLANT_SUCCESS',
	GET_PLANT_FAILURE: 'GET_PLANT_FAILURE',

	WATER_PLANT_START: 'WATER_PLANT_START',
	WATER_PLANT_SUCCESS: 'WATER_PLANT_SUCCESS',
	WATER_PLANT_FAILURE: 'WATER_PLANT_FAILURE',

	STOP_WATERING_PLANT: 'STOP_WATERING_PLANT',

	ADD_PLANT_TO_WATER_LIST: 'ADD_PLANT_TO_WATER_LIST',
	REMOVE_PLANT_FROM_WATER_LIST: 'REMOVE_PLANT_FROM_WATER_LIST',
	REMOVE_PLANTS_FROM_WATER_LIST: 'REMOVE_PLANTS_FROM_WATER_LIST',

	WATER_MULTIPLE_PLANTS_START: 'WATER_MULTIPLE_PLANTS_START',
	WATER_MULTIPLE_PLANTS_SUCCESS: 'WATER_MULTIPLE_PLANTS_SUCCESS',
	WATER_MULTIPLE_PLANTS_FAILURE: 'WATER_MULTIPLE_PLANTS_FAILURE'
};

export default types;